### ISSUE TITLE
Unable to parse input: invalid character '-' in numeric literal

### ISSUE THREAD

**Issue by alecksalecks** [sindrel/excalidraw-converter#27]
Error Message:  `Unable to parse input: invalid character '-' in numeric literal`
[drawing.zip](https://github.com/sindrel/excalidraw-converter/files/12879772/drawing.zip)

I get this error for any drawing created in Excalidraw for Obsidian plugin.

**Comment by alecksalecks** [comment]
I've found a workaround, I'm copy and pasting the contents of the file into the Excalidraw site. But then I get the error:
`Unable to parse input: json: cannot unmarshal number 0.5 into Go struct field .elements.strokeWidth of type int64`
I can then set the thickness of all thes to the lowest setting and then I can save and convert files.

**Comment by sindrel** [comment]
Hi @alecksalecks! Thanks for reporting the issue.

The issue with element thickness should now be fixed in the latest release: [v1.2.1](https://github.com/sindrel/excalidraw-converter/releases/tag/v1.2.1).

I also looked into the issue with diagrams created in Obsidian. Files created by the Excalidraw for Obsidian plugin seem to be saved in a markdown format designed for Obsidian. This adds some metadata that are unparseable by Excalidraw.

However, if you use the "Export image" dialog in the page you want to save, and choose the "Excalidraw" button, it should be saved in a format that should work (JSON):

![image](https://github.com/sindrel/excalidraw-converter/assets/35308882/b73517ae-41fb-485e-abab-e17dda00edf4)

If you use the latest version of Excalidraw Converter, and use the export dialog, you should be able to convert diagrams without workarounds.

Let me know if it fixes your problem!

**Comment by alecksalecks** [comment]
Yep that does fix it thanks for the help.
